### ISSUE TITLE
Unable to createSQLContext

### ISSUE THREAD

**Issue by hannah-smudge** [skiptools/skip-sql#1]
Hi, I tried running the  same methof `createSQLContext()` from DatabakeApp to my own app and I am getting this error:

![Screenshot 2023-11-20 at 10 37 21 AM](https://github.com/skiptools/skip-sql/assets/97433938/162a0f57-1323-4f54-af30-82baa7f04d96)

I already import the SkipSQL. Am I missing anything? Thanks

**Comment by aabewhite** [comment]
Sorry for the trouble! We may not be able to debug the issue without significantly more context, but in the interests of getting you unstuck: have you tried doing what the error message suggests? In your flags: argument, try fully qualifying the flag names: SQLContext.OpenFlags.readWrite, SQLContext.OpenFlags.create. Please let us know how it goes.

**Comment by hannah-smudge** [comment]
Hi @aabewhite , Thanks for the speedy reply. 

Yeah I tried adding that one
![Screenshot 2023-11-20 at 11 40 37 AM](https://github.com/skiptools/skip-sql/assets/97433938/60fc8002-e01b-4319-a3ea-1b3c5ac540b8)
 And i still get a build error. This is the error logs:
```
ld: Undefined symbols:
  SkipSQL.SQLContext.exec(sql: Swift.String, parameters: [SkipSQL.SQLValue]) throws -> (), referenced from:
      closure #1 () throws -> () in RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
      closure #1 () throws -> () in RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
  SkipSQL.SQLContext.__allocating_init(path: Swift.String, flags: SkipSQL.SQLContext.OpenFlags?, logLevel: __C.os_log_type_t?) throws -> SkipSQL.SQLContext, referenced from:
      RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
  SkipSQL.SQLContext.mutex<A>(block: () throws -> A) throws -> A, referenced from:
      RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
  SkipSQL.SQLContext.OpenFlags.create.unsafeMutableAddressor : SkipSQL.SQLContext.OpenFlags, referenced from:
      RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
  SkipSQL.SQLContext.OpenFlags.readWrite.unsafeMutableAddressor : SkipSQL.SQLContext.OpenFlags, referenced from:
      RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
  type metadata for SkipSQL.SQLContext.OpenFlags, referenced from:
      RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
      lazy protocol witness table accessor for type SkipSQL.SQLContext.OpenFlags and conformance SkipSQL.SQLContext.OpenFlags : Swift.SetAlgebra in SkipSQL in RssFeed.o
  protocol conformance descriptor for SkipSQL.SQLContext.OpenFlags : Swift.SetAlgebra in SkipSQL, referenced from:
      lazy protocol witness table accessor for type SkipSQL.SQLContext.OpenFlags and conformance SkipSQL.SQLContext.OpenFlags : Swift.SetAlgebra in SkipSQL in RssFeed.o
  type metadata accessor for SkipSQL.SQLContext, referenced from:
      RssFeed.createSQLContext(in: Foundation.URL) throws -> SkipSQL.SQLContext in RssFeed.o
  type metadata for SkipSQL.SQLValue, referenced from:
      default argument 1 of SkipSQL.SQLContext.exec(sql: Swift.String, parameters: [SkipSQL.SQLValue]) throws -> () in RssFeed.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am using skip-sql version 0.3.5

**Comment by aabewhite** [comment]
I see. Can you post your Package.swift please? 

This looks like an error another user saw when they did not add the dependency in Package.swift. Could that be the case?

**Comment by hannah-smudge** [comment]
Thanks for your help. 

When I added the skip-sql in Package.swift, it was built successfully. 



![Screenshot 2023-11-20 at 11 59 28 AM](https://github.com/skiptools/skip-sql/assets/97433938/8ca71539-49bc-46a8-b72b-7fae6b841ce1)

Closing this now.
