### ISSUE TITLE
SkipSQLPlus throwing java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by benford-servicem8** [skiptools/skip-sql#2]
Hey Team, 

We're getting the following exception when attempting to use SQLPlus (setting SQLContext `configuration: .plus`)

Caused by: java.lang.UnsatisfiedLinkError: Can't obtain peer field ID for class com.sun.jna.Pointer
07-29 10:08:13.579 15304 15345 I .app.skip:   at void com.sun.jna.Native.initIDs() (SourceFile:-2)
07-29 10:08:13.579 15304 15345 I .app.skip:   at void com.sun.jna.Native.<clinit>() (SourceFile:-1)
07-29 10:08:13.579 15304 15345 I .app.skip:   at void skip.sql.SQLiteJNALibrary.<init>() (SourceFile:-1)
07-29 10:08:13.579 15304 15345 I .app.skip:   at void skip.sql.SQLiteJNALibrary.<clinit>() (SourceFile:-1)
07-29 10:08:13.579 15304 15345 I .app.skip:   at void skip.sql.SQLiteConfiguration.<clinit>() (SourceFile:-1)
07-29 10:08:13.579 15304 15345 I .app.skip:   at void skip.sql.SQLContext.<init>(java.lang.String, skip.sql.SQLContext$OpenFlags, skip.foundation.SkipLogger$LogType, skip.sql.SQLiteConfiguration, int, A3.k) (SourceFile:10)

`ben@MacBookPro skip-sql % skip test
[✓] Check Swift Package (1.51s)
[✓] Build Project (27.94s)
[✗] Test project (136.74s)
| Test            | Case                      | Swift | Kotlin |
| --------------- | ------------------------- | ----- | ------ |
| SQLContextTests | testSQLite                | PASS  | FAIL   |
| SQLContextTests | testSQLiteInterrupt       | PASS  | FAIL   |
| SQLContextTests | testSQLiteNamedParameters | PASS  | FAIL   |
| SQLContextTests | testSQLitePerformance     | PASS  | FAIL   |
| SQLPlusTests    | testSQLCipher             | PASS  | FAIL   |
| SQLPlusTests    | testSQLPlus               | PASS  | FAIL   |
| SQLPlusTests    | testSQLiteJSON            | PASS  | FAIL   |
|                 |                           | 100%  | 0%     |

| Test            | Case                      | Swift | Kotlin |
| --------------- | ------------------------- | ----- | ------ |
| SQLContextTests | testSQLite                | PASS  | PASS   |
| SQLContextTests | testSQLiteInterrupt       | PASS  | PASS   |
| SQLContextTests | testSQLiteNamedParameters | PASS  | PASS   |
| SQLContextTests | testSQLitePerformance     | PASS  | PASS   |
|                 |                           | 100%  | 100%   |

`

Skip Checkup:
`ben@MacBookPro skip-sql % skip checkup
[✓] Skip version 0.10.7 (= 0.10.7)
[✓] macOS version 15.0 (> 13.5.0)
[✓] macOS architecture: ARM
[✓] Swift version 6.0 (> 5.9.0)
[✓] Xcode version 16.0 (> 15.0.0)
[✓] Xcode tools SDKs: 9
[✓] Homebrew version 4.3.10 (> 4.1.0)
[✓] Gradle version 8.9 (> 8.6.0)
[✓] Java version 22.0.1 (> 21.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2024.1
[✓] Android tools SDKs: 2
[✓] Resolve dependencies (14.32s)
[✓] Build hello-skip (15.33s)
[✓] Test Swift (8.3s)
[✓] Test Kotlin (153.76s)
[✓] Archive iOS ipa (28.1s)
[✓] Assemble HelloSkip-release.ipa 39 KB
[✓] Verify HelloSkip-release.ipa 39 KB
[✓] Assembling Android apk (503.34s)
[✓] Verify HelloSkip-release.apk 12.7 MB
[✓] Check Swift Package (0.36s)
[✓] Check Skip Updates: 0.10.7
[✓] Skip 0.10.7 checkup succeeded in 727.04s`

**Comment by marcprux** [comment]
This is running `skip test` against a fresh checkout of skip-sql.git? It is working for me, as well as in CI. Could you try deleting the `Package.resolved` file and `.build` folder and trying once more?

Also, I notice you are running Swift version 6.0 and Xcode version 16.0, which isn't well tested at this point. If you still have the non-beta version of Xcode 15.4 installed, could you try switching to it with `xcode-select --switch …` and seeing if that changes things?

**Comment by benford-servicem8** [comment]
Ok I'm closer: 
* Running Xcode 15.4 correctly pases `skip test` as expected, 
* The issue only occurs when testflighting to the play store, so i think i've tracked it down to the settings in build.gradle.kts, buildTypes.release has `isMinifyEnabled = true` and `isShrinkResources = true`, setting both of these to false resolves the issue

Would this mean the correct fix is to add `-keep class com.sun.jna.** { *; }` to proguard-rules.pro?

**Comment by marcprux** [comment]
Ahh, yes, you are probably right about that. Let us know if the "-keep" line helps, and we will add it to the docs and/or update the default proguard rules accordingly.

**Comment by marcprux** [comment]
BTW, you might also need to `-keep class skip.sql.** { *; }`

**Comment by benford-servicem8** [comment]
Thanks Marc, 

Have tried various combinations but haven't been able to solve it - luckily i've worked out it's reproducible in the the skip-databake project as well. 

Steps to reproduce: 
* Checkout skip-databake
* echo "-keep class com.sun.jna.** { *; }" >> Android/app/proguard-rules.pro
* cd Android ; fastlane assemble

This (hopefully) results in the following error: 
`ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/admin/builds/skip/skip-app/skipapp-databake/.build/Android/app/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class java.awt.Component (referenced from: long com.sun.jna.Native$AWT.getComponentID(java.lang.Object) and 3 other contexts)
Missing class java.awt.GraphicsEnvironment (referenced from: long com.sun.jna.Native$AWT.getComponentID(java.lang.Object))
Missing class java.awt.HeadlessException (referenced from: long com.sun.jna.Native$AWT.getComponentID(java.lang.Object))
Missing class java.awt.Window (referenced from: long com.sun.jna.Native$AWT.getWindowID(java.awt.Window) and 2 other contexts)
w: Detected multiple Kotlin daemon sessions at 
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.`

I'm not sure why the error doesn't occur until you add `-keep class com.sun.jna`, but it does seem required as otherwise there are jna errors in the resulting build, and the release is also fine if minify / shrink are disabled.

**Comment by marcprux** [comment]
I suspect this particular error is coming from the fact that JNA has some built-in support for the old AWT classes, which are absent from Android (e.g.,: https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Native.java#L2427C26-L2427C29). And so Proguard is trying to reference these classes to determine if they should be minified.

Looking at https://github.com/java-native-access/jna/blob/master/native/dispatch.c#L2862, it looks like it is actually the `com.sun.jna.Pointer.peer` field is it is trying to load through reflection, so could you instead try to `-keep class com.sun.jna.** { *; }` and see if that changes anything?

**Comment by benford-servicem8** [comment]
Legend! That fixed it, thank you.

**Comment by marcprux** [comment]
Great! We will add `com.sun.jna.Pointer` to the default `proguard-rules.pro` file generated by `skip init` so that future projects don't run into this issue. Thanks for the help in debugging it.
